# Generated by Django 6.0.4 on 2026-04-29 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL / MariaDB'), ('postgres', 'PostgreSQL'), ('mongo', 'MongoDB'), ('oracle', 'Oracle')], max_length=20)),
                ('endpoint', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('sync_mode', models.CharField(choices=[('push', 'Continuous Push'), ('poll', 'Interval Polling (1m)')], max_length=10)),
                ('status', models.CharField(default='Connected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
