# Generated by Django 6.0.2 on 2026-04-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('REGEX', 'Regular Expression'), ('THRESHOLD', 'Frequency Threshold'), ('SEVERITY', 'Severity Based')], max_length=20)),
                ('pattern', models.CharField(help_text='Regex pattern or event type name', max_length=255)),
                ('threshold', models.IntegerField(default=1, help_text='Number of occurrences required (for THRESHOLD type)')),
                ('time_window', models.IntegerField(default=5, help_text='Time window in minutes (for THRESHOLD type)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='anomaly_score',
            field=models.FloatField(default=0.0),
        ),
    ]
