"""Phase 7A: generate the MITRE mapping audit artifact.

Read-only with respect to everything except its own output files. Calls the
live, unmodified `forecasting.mitre_mapping.MitreMapper` for every real
CIC-IDS2018 attack label documented in `NetOracle/reports/cic_ids2018_audit.json`
/ `NetOracle/docs/cic_ids2018_audit.md` (Phase 2 dataset audit), so the audit
table is guaranteed consistent with the actual code, not hand-transcribed.

Outputs:
    NetOracle/docs/mitre_mapping_audit.csv
    NetOracle/docs/MITRE_MAPPING_AUDIT.md

Does not touch data/, experiments/, or any Phase 3-5/Phase 6B artifact.
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from forecasting.mitre_mapping import MitreMapper

OUTPUT_DIR = Path(__file__).resolve().parents[1] / "docs"
CSV_PATH = OUTPUT_DIR / "mitre_mapping_audit.csv"
MD_PATH = OUTPUT_DIR / "MITRE_MAPPING_AUDIT.md"

# The 15 real, non-header attack labels confirmed present in the CIC-IDS2018
# temporal dataset (data/windows/*.csv), per NetOracle/docs/cic_ids2018_audit.md
# and NetOracle/reports/cic_ids2018_audit.json (Phase 2 dataset audit). "Label"
# (repeated header rows) is excluded upstream by build_temporal_dataset.py and
# is not an attack class.
REAL_DATASET_LABELS = [
    "Benign",
    "Bot",
    "DDoS attack-HOIC",
    "DDoS attacks-LOIC-HTTP",
    "DDoS attack-LOIC-UDP",
    "DoS attacks-Hulk",
    "DoS attacks-SlowHTTPTest",
    "DoS attacks-GoldenEye",
    "DoS attacks-Slowloris",
    "FTP-BruteForce",
    "SSH-Bruteforce",
    "Infiltration",
    "Brute Force -Web",
    "Brute Force -XSS",
    "SQL Injection",
]

# Known aliases of the real labels above (shorthand / reordered spellings).
# Not independently-occurring dataset labels; included for completeness and
# to document that they resolve to the SAME mapping as their canonical label.
ALIASES = [
    ("Infilteration", "Infiltration"),
    ("LOIC-HTTP", "DDoS attacks-LOIC-HTTP"),
    ("LOIC-UDP", "DDoS attack-LOIC-UDP"),
    ("Web Brute Force", "Brute Force -Web"),
    ("XSS", "Brute Force -XSS"),
]

FIELDNAMES = [
    "dataset_label",
    "normalized_label",
    "mitre_stage",
    "technique_id",
    "confidence",
    "evidence_type",
    "notes",
]


def build_rows() -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for label in REAL_DATASET_LABELS:
        prediction = MitreMapper.from_attack_label(label)
        rows.append(
            {
                "dataset_label": label,
                "normalized_label": MitreMapper.normalize_label(label),
                "mitre_stage": prediction.stage.name,
                "technique_id": prediction.technique or "",
                "confidence": prediction.confidence,
                "evidence_type": prediction.evidence_type,
                "notes": prediction.notes or prediction.description or "",
            }
        )
    for alias, canonical in ALIASES:
        prediction = MitreMapper.from_attack_label(alias)
        rows.append(
            {
                "dataset_label": f"{alias} (alias of {canonical})",
                "normalized_label": MitreMapper.normalize_label(alias),
                "mitre_stage": prediction.stage.name,
                "technique_id": prediction.technique or "",
                "confidence": prediction.confidence,
                "evidence_type": prediction.evidence_type,
                "notes": prediction.notes or prediction.description or "",
            }
        )
    return rows


def write_csv(rows: list[dict[str, object]]) -> None:
    with CSV_PATH.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=FIELDNAMES)
        writer.writeheader()
        writer.writerows(rows)


def write_markdown(rows: list[dict[str, object]]) -> None:
    lines = [
        "# MITRE Mapping Audit (Phase 7A)",
        "",
        "Generated by `NetOracle/scripts/generate_mitre_mapping_audit.py`, which calls the "
        "live `forecasting.mitre_mapping.MitreMapper` for every real CIC-IDS2018 attack label "
        "confirmed present in the temporal dataset (see `NetOracle/docs/cic_ids2018_audit.md`), "
        "so this table is guaranteed consistent with the actual mapping code, not hand-transcribed.",
        "",
        "`evidence_type` legend:",
        "- `authoritative_generic`: a standard, widely-cited ATT&CK technique/tactic association "
        "for this attack class (not a per-flow verified citation, but not a guess).",
        "- `heuristic`: stage chosen by categorical judgment, no specific technique asserted.",
        "- `heuristic_reasoned`: a corrected heuristic judgment with an explicit rationale (see notes).",
        "- `heuristic_uncertain`: explicitly flagged as uncertain/ambiguous -- do not treat as authoritative.",
        "- `not_applicable`: not an attack, or no mapping found.",
        "",
        "| Dataset label | Normalized label | MITRE stage | Technique | Confidence | Evidence type | Notes |",
        "|---|---|---|---|---:|---|---|",
    ]
    for row in rows:
        notes = str(row["notes"]).replace("|", "\\|").replace("\n", " ")
        lines.append(
            f"| {row['dataset_label']} | `{row['normalized_label']}` | {row['mitre_stage']} | "
            f"{row['technique_id'] or '—'} | {row['confidence']:.2f} | {row['evidence_type']} | {notes} |"
        )
    lines += [
        "",
        "## Confirmed Phase 7A fixes",
        "",
        "- **SQL Injection** previously fell through every match rule to `BENIGN` / confidence "
        "`0.0` (\"Unknown attack type\"). Now resolves to `INITIAL_ACCESS` / `T1190` "
        "(Exploit Public-Facing Application).",
        "- **Brute Force -XSS** previously matched the generic `brute force` keyword via substring "
        "containment and was misclassified as `CREDENTIAL_ACCESS` / `T1110`. Now resolves to "
        "`INITIAL_ACCESS` / `T1190` via an exact canonical match, which is checked before the "
        "substring fallback ever runs.",
        "- **Infiltration** is retained at `LATERAL_MOVEMENT` but is now explicitly flagged "
        "`heuristic_uncertain` with a documented rationale: the dataset provides one flow-level "
        "label regardless of which real kill-chain sub-phase (Initial Access/Execution via the "
        "dropped file, vs. Discovery/Lateral Movement via internal probing) produced a given flow.",
        "",
        "## Aggregation policy for multiple future-horizon labels",
        "",
        "`MitreMapper.from_label_set(labels)` (new in Phase 7A) maps a `;`-joined label set "
        "(matching the dataset's own `future_attack_types` column format) to a single "
        "`MitrePrediction` by: (1) mapping each label independently via `from_attack_label`, "
        "(2) selecting the mapping with the highest `MitreStage` value as the dominant future risk, "
        "(3) breaking ties by the alphabetically-first normalized label for full determinism, "
        "(4) returning `BENIGN`/confidence `0.0` for no labels. This is a **target/label construction "
        "utility only** -- it is not wired into any model input in this phase.",
        "",
    ]
    MD_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    rows = build_rows()
    write_csv(rows)
    write_markdown(rows)
    print(f"Wrote {CSV_PATH}")
    print(f"Wrote {MD_PATH}")
    print(f"{len(rows)} rows ({len(REAL_DATASET_LABELS)} real labels + {len(ALIASES)} aliases)")


if __name__ == "__main__":
    main()
